// 状态改变类型
export const SET_SINGER = 'SET_SINGER';
// 设置播放歌曲
export const SET_PLAYING_STATE = 'SET_PLAYING_STATE';
export const SET_FULL_SCREEN = 'SET_FULL_SCREEN';
export const SET_PLAY_LIST = 'SET_PLAY_LIST';
export const SET_SEQUENCE_LIST = 'SET_SEQUENCE_LIST';
export const SET_PLAY_MODE = 'SET_PLAY_MODE';
export const SET_CURRENT_INDEX = 'SET_CURRENT_INDEX';

export const SET_DISTLIST = 'SET_DISTLIST';
export const SET_TOPLIST = 'SET_TOPLIST';

export const SET_SEARCH_HISTORY = 'SET_SEARCH_HISTORY';

export const SET_PLAY_HISTORY = 'SET_PLAY_HISTORY';

export const SET_FAVORITE_LIST = 'SET_FAVORITE_LIST';
